### PR TITLE
retargeted tests to .NetCore 3.1

### PR DESCRIPTION
**Pull request by norvegec**

### CODE REVIEW

**Comment by jkonecki** [comment]
Hello Dmitry - thank you very much for your PR.
Could you please take a look at the failing build? 

https://dev.azure.com/jkonecki/Eveneum/_build/results?buildId=182&view=logs&j=fd490c07-0b22-5182-fac9-6d67fe1e939b&t=0a4209d8-dbda-5f52-f4a1-2fb1b9c3340a&l=148

**Comment by norvegec** [comment]
> Hello Dmitry - thank you very much for your PR.
> Could you please take a look at the failing build?
> 
Hi, Jakub, I've fixed some things to make it work. Now it fails with something related to SpecFlow binding. 
I'm not that advanced in SpecFlow to tell what's wrong, could you give me a hand here?
Sample stack trace of a failed test:
```csharp
System.ArgumentNullException : Value cannot be null. (Parameter 'key')
TearDown : System.NullReferenceException : Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.FindAttributeConstructorArg(ParameterInfo parameterInfo, Dictionary`2 namedAttributeValues)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.<>c__DisplayClass8_0.<CreateAttribute>b__7(ParameterInfo p)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.CreateAttribute(Attribute attribute)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.GetAttributes(IEnumerable`1 customAttributes)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.CreateBindingSourceMethod(MethodInfo methodDefinition)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.BuildBindingsFromType(Type type)
   at TechTalk.SpecFlow.Bindings.Discovery.RuntimeBindingRegistryBuilder.BuildBindingsFromAssembly(Assembly assembly)
   at TechTalk.SpecFlow.TestRunnerManager.BuildBindingRegistry(IEnumerable`1 bindingAssemblies)
   at TechTalk.SpecFlow.TestRunnerManager.InitializeBindingRegistry(ITestRunner testRunner)
   at TechTalk.SpecFlow.TestRunnerManager.CreateTestRunner(Int32 threadId)
   at TechTalk.SpecFlow.TestRunnerManager.GetTestRunnerWithoutExceptionHandling(Int32 threadId)
   at TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(Int32 threadId)
   at TechTalk.SpecFlow.TestRunnerManager.GetTestRunner(Assembly testAssembly, Nullable`1 managedThreadId)
   at Eveneum.Tests.AdvancedFeature.FeatureSetup()
```

**Comment by norvegec** [comment]
Also it might work if you replace devops task that runs test in full .Net Framework with [task that runs them in .Net Core](https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/dotnet-core?view=azure-devops&tabs=dotnetfive#collect-code-coverage)

**Comment by jkonecki** [comment]
@norvegec I'll take a look at it over the weekend. Thanks!

**Pull request closed without merging**
