### PR TITLE
Introduce options when reading a streams and reading a specific header document

### PR DESCRIPTION
**Pull request by ThomasVandenbon**
- Exposes `ReadHeader` on `IReadStream` to allow reading a header document, without reading the events on the stream. For example, this could be used to read meta-data on the stream, without reading the stream.
- Introduce a new method to read the events on a stream (`ReadStream`) which includes `ReadStreamOptions` to have a higher degree of control in how the stream is read.

See #28

### CODE REVIEW

**Comment by ThomasVandenbon** [comment]
@jkonecki 

I've marked the PR as a draft as I'm still struggling with tests. I can't seem to setup my specflow account to be able to generate tests. Some tests should at least be added to verify the new ReadHeader and ReadStream options.

Additionally, I've added an extra `MaxItemCount` to the `ReadStreamOptions` which we didn't discuss in #28 but does allow the previous behaviour in `ReadStreamAsOfVersion` where a fixed value of `100` was used, rather than the "global" `QueryMaxItemCount`. I feel this adds some extra flexibility and usability.

**Comment by jkonecki** [comment]
> I can't seem to setup my specflow account to be able to generate tests.
I don't think you need to set up any account - at least I don't have one.

I'll work on the tests and will make other tiny changes.

**Comment by jkonecki** [comment]
Hello Thomas, could you please give me permission to push changes to `in-place_copy-replace_features` branch on `ThomasVandenbon/Eveneum`? I plan to finish refactoring and tests tomorrow.

**Review by jkonecki — APPROVED** [review]

**Comment by ThomasVandenbon** [comment]
@jkonecki Looks good!
Thank you for the refactoring and the extra tests!

**Pull request merged**
